baseURL = "https://jlakritz.github.io/brightlight-theatre/"
languageCode = "en-gb"
title = "Brightlight Theatre"
enableRobotsTXT = true
paginate = 12
summaryLength = 30
canonifyURLs = true

[params]
  description = "Award-winning theatre in Surrey creating extraordinary productions that thrill, captivate and inspire."
  email = "info@brightlight-theatre.co.uk"
  charity_number = "1185359"
  
[[menu.main]]
  name = "Productions"
  url = "/productions/"
  weight = 10

[[menu.main]]
  name = "News"
  url = "/news/"
  weight = 20

[[menu.main]]
  name = "About us"
  url = "/about/"
  weight = 30

[[menu.main]]
  name = "Join us"
  url = "/join-us/"
  weight = 40

[[menu.main]]
  name = "Contact us"
  url = "/contact/"
  weight = 50
